---
- name: generate MOTD
  shell: |
    echo " " > "../ssh/tmp-motd-{{ inventory_hostname }}"
    figlet -f "{{ role_path }}/vars/{{ ascii_font }}.flf" "{{ text }}" >> "../ssh/tmp-motd-{{ inventory_hostname }}"
    echo " " >> "../ssh/tmp-motd-{{ inventory_hostname }}"
  delegate_to: localhost
  tags: motd

- name: copy MOTD to remote host
  copy:
    src: "../ssh/tmp-motd-{{ inventory_hostname }}"
    dest: "{{ path_motd }}"
  tags: motd

- name: remove temp file
  file:
    path: "../ssh/tmp-motd-{{ inventory_hostname }}"
    state: absent
  delegate_to: localhost
  tags: motd
